/**
 * seedData.js - Canonical Raw Seed Dataset
 * Part of E-Waste Bridge Database Layer (SIH 2026 PS-2)
 *
 * Implements the 7 mandatory datasets demanded by the E-Waste Management Rules 2022:
 * 1. Material Taxonomy (including Motors & Magnet Assemblies - Neodymium)
 * 2. Price Benchmarks & Volatility Indices
 * 3. 7-Day Historical Price Time-Series
 * 4. Authorized Recyclers Registry
 * 5. Minimalist Collector Profiles
 * 6. Transactions & Traceability Event Stream
 * 7. Field Research Case Studies & Unit Economics Model
 */

export const MATERIALS_SEED = [
  {
    material_id: "smartphones",
    category: "Telecom & Consumer",
    sub_category: "Touchscreen Smartphone Assemblies",
    cpcb_code: "ITEW15",
    name_en: "Mobile Phones & Smartphones",
    name_hi: "मोबाइल फोन और स्मार्टफोन",
    name_mr: "मोबाईल फोन आणि स्मार्टफोन्स",
    unit: "kg",
    base_benchmark_rate: 380,
    min_market_rate: 340,
    max_market_rate: 420,
    hazard_level: "MEDIUM",
    hazard_flags: ["Lithium-Ion Battery", "Cobalt Fire Risk"],
    safety_warning_en: "Ensure lithium battery is intact. Do not puncture or expose to flame.",
    safety_warning_hi: "लिथियम बैटरी की जांच करें। इसे नुकीली चीजों से दूर रखें।",
    safety_warning_mr: "लिथियम बॅटरी सुरक्षित ठेवा. उष्णतेपासून दूर ठेवा.",
    critical_raw_materials: ["Cobalt", "Lithium", "Gold", "Copper"],
    visual_cues: ["Glass front screen", "Rear camera module", "USB-C port"]
  },
  {
    material_id: "laptops",
    category: "IT & Computing",
    sub_category: "Portable Notebook PC Units",
    cpcb_code: "ITEW2",
    name_en: "Laptops & Notebooks",
    name_hi: "लैपटॉप और नोटबुक",
    name_mr: "लॅपटॉप आणि नोटबुक्स",
    unit: "kg",
    base_benchmark_rate: 210,
    min_market_rate: 190,
    max_market_rate: 240,
    hazard_level: "MEDIUM",
    hazard_flags: ["Built-in Battery", "Mercury/CCFL in older backlights"],
    safety_warning_en: "Keep casing closed. Do not attempt unvented cell extraction.",
    safety_warning_hi: "लैपटॉप को बंद रखें। बैटरी को बिना सुरक्षा उपकरण न निकालें।",
    safety_warning_mr: "लॅपटॉप बंद ठेवा. बॅटरी हाताने काढण्याचा प्रयत्न करू नका.",
    critical_raw_materials: ["Tantalum", "Gold", "Copper", "Lithium"],
    visual_cues: ["Foldable chassis", "Keyboard trackpad", "Display lid"]
  },
  {
    material_id: "pcb",
    category: "High-Grade Boards",
    sub_category: "Server & Computer Motherboards",
    cpcb_code: "ITEW23",
    name_en: "Printed Circuit Boards (PCBs)",
    name_hi: "सर्किट बोर्ड और मदरबोर्ड",
    name_mr: "मदरबोर्ड व पीसीबी स्क्रॅप",
    unit: "kg",
    base_benchmark_rate: 350,
    min_market_rate: 310,
    max_market_rate: 420,
    hazard_level: "HIGH",
    hazard_flags: ["Lead Solder", "Brominated Flame Retardants (BFR)", "Acid Leaching Risk"],
    safety_warning_en: "STRICT WARNING: Do not attempt open-pan burning or acid bath extraction. Route directly to authorized CPCB refiners.",
    safety_warning_hi: "सख्त चेतावनी: मदरबोर्ड पर तेजाब न डालें और न ही इसे जलाएं। यह फेफड़ों के लिए अत्यंत जहरीला है।",
    safety_warning_mr: "कडक इशारा: पीसीबी जाळू नका किंवा ऍसिड वापरू नका. CPCB प्रमाणित रिफायनरकडे पाठवा.",
    critical_raw_materials: ["Gold", "Silver", "Palladium", "Copper"],
    visual_cues: ["Green/Blue FR-4 substrate", "Gold connector fingers", "Microchips"]
  },
  {
    material_id: "batteries",
    category: "Energy Storage",
    sub_category: "Li-Ion & Lead Acid Cells",
    cpcb_code: "CEEW4",
    name_en: "Batteries (Li-Ion & Lead-Acid)",
    name_hi: "लिथियम व लेड-एसिड बैटरी",
    name_mr: "लिथियम व लेड-अॅसिड बॅटरी",
    unit: "kg",
    base_benchmark_rate: 95,
    min_market_rate: 80,
    max_market_rate: 110,
    hazard_level: "CRITICAL",
    hazard_flags: ["Thermal Runaway Hazard", "Electrolyte Spillage", "Toxic Gas"],
    safety_warning_en: "CRITICAL SAFETY: Store in non-conductive, fire-retardant container. Never puncture terminals.",
    safety_warning_hi: "अति-गंभीर सुरक्षा: बैटरी को सूखी जगह पर रखें। शॉर्ट सर्किट या आग से बचाएं।",
    safety_warning_mr: "अतिसंवेदनशील: बॅटरी कोरड्या जागेत ठेवा. शॉर्ट सर्किट किंवा आग टाळा.",
    critical_raw_materials: ["Lithium", "Cobalt", "Nickel", "Lead"],
    visual_cues: ["Pouch cell", "Cylindrical 18650 cells", "Prismatic packs"]
  },
  {
    material_id: "cables",
    category: "Ferrous & Non-Ferrous",
    sub_category: "Copper Wires & Harnesses",
    cpcb_code: "NFM1",
    name_en: "Copper Wires & Cables",
    name_hi: "तांबे के तार और केबल",
    name_mr: "तांब्याची वायर व केबल्स",
    unit: "kg",
    base_benchmark_rate: 180,
    min_market_rate: 165,
    max_market_rate: 205,
    hazard_level: "LOW",
    hazard_flags: ["Dioxin Emission on Open Burning"],
    safety_warning_en: "DO NOT BURN insulation wire in open air (violates CPCB Clean Air norms). Route to mechanical strippers.",
    safety_warning_hi: "तारों को खुले में न जलाएं। इसका धुआं कैंसरकारी होता है। छीलने के लिए कटर का उपयोग करें।",
    safety_warning_mr: "वायर उघड्यावर जाळू नका. प्लास्टिक जाळल्याने विषारी धूर होतो. कटर वापरा.",
    critical_raw_materials: ["Pure Copper (Cu 99%)"],
    visual_cues: ["PVC insulated bundles", "Braided copper wire", "Power cords"]
  },
  {
    material_id: "motors_magnets",
    category: "Critical Rare Earths",
    sub_category: "Motors & Magnet Assemblies (Neodymium)",
    cpcb_code: "EEM1",
    name_en: "Motors & Magnet Assemblies",
    name_hi: "मोटर और नियोडिमियम चुंबक",
    name_mr: "मोटार व मॅग्नेट असेंब्ली (नियोडिमियम)",
    unit: "kg",
    base_benchmark_rate: 120,
    min_market_rate: 105,
    max_market_rate: 140,
    hazard_level: "MEDIUM",
    hazard_flags: ["Pinch Hazard from Powerful Magnets", "Fine Metal Dust"],
    safety_warning_en: "High magnetic strength: keep separated from watches and pacemakers. Do not grind dry.",
    safety_warning_hi: "मजबूत चुंबक: घड़ियों और इलेक्ट्रॉनिक उपकरणों से दूर रखें। सूखा न पीसें।",
    safety_warning_mr: "शक्तिशाली चुंबक: घड्याळांपासून दूर ठेवा. कोरडे कापू नका.",
    critical_raw_materials: ["Neodymium (Nd)", "Dysprosium (Dy)", "Copper", "Silicon Steel"],
    visual_cues: ["Hard drive magnets", "Fan/compressor stator coils", "Heavy metal rotor"]
  },
  {
    material_id: "crt",
    category: "Displays & Monitors",
    sub_category: "Cathode Ray Picture Tubes",
    cpcb_code: "ITEW11",
    name_en: "CRT Displays & Glass Tubes",
    name_hi: "सीआरटी मॉनिटर और पिक्चर ट्यूब",
    name_mr: "सीआरटी मॉनिटर व काच ट्यूब",
    unit: "kg",
    base_benchmark_rate: 45,
    min_market_rate: 35,
    max_market_rate: 55,
    hazard_level: "HIGH",
    hazard_flags: ["Leaded Funnel Glass (~2kg lead per tube)", "Vacuum Implosion"],
    safety_warning_en: "HANDLE WITH GLOVES: Avoid striking neck of tube. High risk of lead dust inhalation if broken.",
    safety_warning_hi: "दस्ताने पहनकर उठाएं: ट्यूब की गर्दन पर चोट न लगाएं। टूटने पर जहरीला सीसा निकलता है।",
    safety_warning_mr: "हातमोजे वापरा: ट्यूब फुटल्यास विषारी शिसे हवेत पसरते. स्क्रीन फुटू देऊ नका.",
    critical_raw_materials: ["Lead", "Phosphor", "Barium Glass"],
    visual_cues: ["Heavy funnel glass", "Electron gun neck", "Curved glass face"]
  },
  {
    material_id: "abs_plastic",
    category: "Mixed Plastics & Polymers",
    sub_category: "Mixed Engineering Plastics & Appliance Shells",
    cpcb_code: "POL1",
    name_en: "Mixed Plastics & ABS Casings",
    name_hi: "मिश्रित प्लास्टिक और उपकरण केसिंग (Mixed Plastics)",
    name_mr: "मिश्रित प्लॅस्टिक व कॅबिनेट (Mixed Plastics)",
    unit: "kg",
    base_benchmark_rate: 30,
    min_market_rate: 26,
    max_market_rate: 34,
    hazard_level: "LOW",
    hazard_flags: ["Flame Retardants (BFR in older chassis)"],
    safety_warning_en: "Keep dry and separated from PVC plastics. Avoid open burning.",
    safety_warning_hi: "प्लास्टिक को सूखा रखें। इसे न जलाएं।",
    safety_warning_mr: "प्लॅस्टिक कोरडे ठेवा. जाळणे टाळा.",
    critical_raw_materials: ["High-Impact Polystyrene (HIPS)", "ABS Polyblend"],
    visual_cues: ["Matte black/grey textured shell", "Flame retardant markings", "Snap clips"]
  },
  {
    material_id: "lcd_panels",
    category: "Displays & Monitors",
    sub_category: "Liquid Crystal Display & LED Flat Panels",
    cpcb_code: "ITEW12",
    name_en: "LCD & LED Display Panels",
    name_hi: "एलसीडी और एलईडी डिस्प्ले स्क्रीन",
    name_mr: "एलसीडी व एलईडी डिस्प्ले स्क्रीन्स",
    unit: "kg",
    base_benchmark_rate: 65,
    min_market_rate: 55,
    max_market_rate: 78,
    hazard_level: "HIGH",
    hazard_flags: ["Mercury Vapor in CCFL Backlights", "Indium Tin Oxide (ITO)", "Liquid Crystal Fluorinated Compounds"],
    safety_warning_en: "DO NOT CRUSH DISPLAY GLASS. Ruptured CCFL cold-cathode lamps release toxic elemental mercury vapor. Keep panels flat and wear cut-resistant gloves.",
    safety_warning_hi: "डिस्प्ले स्क्रीन को न तोड़ें। पुरानी ट्यूब टूटने पर जहरीला पारा (मर्करी) गैस निकलती है। स्क्रीन को समतल रखें।",
    safety_warning_mr: "डिस्प्ले काच फोडू नका. जुन्या सीसीएफएल बॅकलाइटमधून विषारी पारा वायू बाहेर पडतो. फ्लॅट स्थितीत सुरक्षित ठेवा.",
    critical_raw_materials: ["Indium (In)", "Tin (Sn)", "Gallium (Ga)", "Optical Glass"],
    visual_cues: ["Flat thin glass sandwich", "LVDS ribbon cable", "Polarizer optical film", "Edge-lit backlight frame"]
  }
];

export const PRICE_BENCHMARKS_SEED = [
  {
    benchmark_id: "bm-smartphones-mmr",
    material_id: "smartphones",
    region_code: "MH-MMR",
    region_name: "Mumbai Metropolitan Region",
    prevailing_buying_rate: 380,
    min_rate: 340,
    max_rate: 420,
    unit: "kg",
    price_trend: "UP_MODERATE",
    trend_percentage: 4.2,
    freshness_score: 0.98,
    sample_transaction_count: 142,
    source_index: "Aggregated CPCB Recycler Intake Index"
  },
  {
    benchmark_id: "bm-laptops-mmr",
    material_id: "laptops",
    region_code: "MH-MMR",
    region_name: "Mumbai Metropolitan Region",
    prevailing_buying_rate: 210,
    min_rate: 190,
    max_rate: 240,
    unit: "kg",
    price_trend: "STABLE",
    trend_percentage: 0.5,
    freshness_score: 0.95,
    sample_transaction_count: 98,
    source_index: "Authorized Refurbisher & Smelter Log"
  },
  {
    benchmark_id: "bm-pcb-mmr",
    material_id: "pcb",
    region_code: "MH-MMR",
    region_name: "Mumbai Metropolitan Region",
    prevailing_buying_rate: 350,
    min_rate: 310,
    max_rate: 420,
    unit: "kg",
    price_trend: "UP_STRONG",
    trend_percentage: 8.5,
    freshness_score: 0.99,
    sample_transaction_count: 215,
    source_index: "Precious Metals Recovery Index (LME Indexed)"
  },
  {
    benchmark_id: "bm-batteries-mmr",
    material_id: "batteries",
    region_code: "MH-MMR",
    region_name: "Mumbai Metropolitan Region",
    prevailing_buying_rate: 95,
    min_rate: 80,
    max_rate: 110,
    unit: "kg",
    price_trend: "STABLE",
    trend_percentage: -0.2,
    freshness_score: 0.92,
    sample_transaction_count: 64,
    source_index: "Authorized Battery Recycler Portal"
  },
  {
    benchmark_id: "bm-cables-mmr",
    material_id: "cables",
    region_code: "MH-MMR",
    region_name: "Mumbai Metropolitan Region",
    prevailing_buying_rate: 180,
    min_rate: 165,
    max_rate: 205,
    unit: "kg",
    price_trend: "UP_MODERATE",
    trend_percentage: 2.4,
    freshness_score: 0.96,
    sample_transaction_count: 180,
    source_index: "Secondary Copper Smelter Rate Sheet"
  },
  {
    benchmark_id: "bm-motors-mmr",
    material_id: "motors_magnets",
    region_code: "MH-MMR",
    region_name: "Mumbai Metropolitan Region",
    prevailing_buying_rate: 120,
    min_rate: 105,
    max_rate: 140,
    unit: "kg",
    price_trend: "UP_STRONG",
    trend_percentage: 6.8,
    freshness_score: 0.94,
    sample_transaction_count: 52,
    source_index: "Rare Earth Magnet Extraction Consortium"
  },
  {
    benchmark_id: "bm-crt-mmr",
    material_id: "crt",
    region_code: "MH-MMR",
    region_name: "Mumbai Metropolitan Region",
    prevailing_buying_rate: 45,
    min_rate: 35,
    max_rate: 55,
    unit: "kg",
    price_trend: "DOWN_MODERATE",
    trend_percentage: -3.0,
    freshness_score: 0.88,
    sample_transaction_count: 38,
    source_index: "Leaded Glass Smelting Partner Bulletin"
  },
  {
    benchmark_id: "bm-plastic-mmr",
    material_id: "abs_plastic",
    region_code: "MH-MMR",
    region_name: "Mumbai Metropolitan Region",
    prevailing_buying_rate: 30,
    min_rate: 26,
    max_rate: 34,
    unit: "kg",
    price_trend: "UP_MODERATE",
    trend_percentage: 5.1,
    freshness_score: 0.94,
    sample_transaction_count: 76,
    source_index: "Polymer Pelletizer & Extruder Daily Sheet",
    effective_date: "2026-09-01",
    valid_until: "2026-09-07"
  },
  {
    benchmark_id: "bm-lcd-mmr",
    material_id: "lcd_panels",
    region_code: "MH-MMR",
    region_name: "Mumbai Metropolitan Region",
    prevailing_buying_rate: 65,
    min_rate: 55,
    max_rate: 78,
    unit: "kg",
    price_trend: "UP_MODERATE",
    trend_percentage: 3.8,
    freshness_score: 0.96,
    sample_transaction_count: 54,
    source_index: "Indium Recovery & Display Dismantling Index",
    effective_date: "2026-09-01",
    valid_until: "2026-09-07"
  }
];

export const PRICE_HISTORY_SEED = [
  // 7-day history for LCD Panels
  { history_id: "hist-lcd-1", material_id: "lcd_panels", recorded_date: "2026-08-30", average_rate: 61, high_rate: 72, low_rate: 52, volume_traded_kg: 280 },
  { history_id: "hist-lcd-2", material_id: "lcd_panels", recorded_date: "2026-08-31", average_rate: 62, high_rate: 74, low_rate: 54, volume_traded_kg: 310 },
  { history_id: "hist-lcd-3", material_id: "lcd_panels", recorded_date: "2026-09-01", average_rate: 63, high_rate: 75, low_rate: 54, volume_traded_kg: 350 },
  { history_id: "hist-lcd-4", material_id: "lcd_panels", recorded_date: "2026-09-02", average_rate: 64, high_rate: 76, low_rate: 55, volume_traded_kg: 320 },
  { history_id: "hist-lcd-5", material_id: "lcd_panels", recorded_date: "2026-09-03", average_rate: 65, high_rate: 78, low_rate: 55, volume_traded_kg: 410 },
  { history_id: "hist-lcd-6", material_id: "lcd_panels", recorded_date: "2026-09-04", average_rate: 65, high_rate: 78, low_rate: 55, volume_traded_kg: 440 },
  { history_id: "hist-lcd-7", material_id: "lcd_panels", recorded_date: "2026-09-05", average_rate: 65, high_rate: 78, low_rate: 55, volume_traded_kg: 420 },

  // 7-day history for Copper Cables
  { history_id: "hist-cab-1", material_id: "cables", recorded_date: "2026-08-30", average_rate: 174, high_rate: 195, low_rate: 160, volume_traded_kg: 840 },
  { history_id: "hist-cab-2", material_id: "cables", recorded_date: "2026-08-31", average_rate: 175, high_rate: 198, low_rate: 162, volume_traded_kg: 920 },
  { history_id: "hist-cab-3", material_id: "cables", recorded_date: "2026-09-01", average_rate: 176, high_rate: 200, low_rate: 164, volume_traded_kg: 1100 },
  { history_id: "hist-cab-4", material_id: "cables", recorded_date: "2026-09-02", average_rate: 178, high_rate: 202, low_rate: 165, volume_traded_kg: 950 },
  { history_id: "hist-cab-5", material_id: "cables", recorded_date: "2026-09-03", average_rate: 179, high_rate: 204, low_rate: 165, volume_traded_kg: 1250 },
  { history_id: "hist-cab-6", material_id: "cables", recorded_date: "2026-09-04", average_rate: 180, high_rate: 205, low_rate: 165, volume_traded_kg: 1400 },
  { history_id: "hist-cab-7", material_id: "cables", recorded_date: "2026-09-05", average_rate: 180, high_rate: 205, low_rate: 165, volume_traded_kg: 1320 },

  // 7-day history for PCBs
  { history_id: "hist-pcb-1", material_id: "pcb", recorded_date: "2026-08-30", average_rate: 320, high_rate: 380, low_rate: 290, volume_traded_kg: 420 },
  { history_id: "hist-pcb-2", material_id: "pcb", recorded_date: "2026-08-31", average_rate: 325, high_rate: 390, low_rate: 300, volume_traded_kg: 480 },
  { history_id: "hist-pcb-3", material_id: "pcb", recorded_date: "2026-09-01", average_rate: 330, high_rate: 400, low_rate: 305, volume_traded_kg: 560 },
  { history_id: "hist-pcb-4", material_id: "pcb", recorded_date: "2026-09-02", average_rate: 338, high_rate: 410, low_rate: 310, volume_traded_kg: 610 },
  { history_id: "hist-pcb-5", material_id: "pcb", recorded_date: "2026-09-03", average_rate: 345, high_rate: 415, low_rate: 310, volume_traded_kg: 690 },
  { history_id: "hist-pcb-6", material_id: "pcb", recorded_date: "2026-09-04", average_rate: 350, high_rate: 420, low_rate: 310, volume_traded_kg: 780 },
  { history_id: "hist-pcb-7", material_id: "pcb", recorded_date: "2026-09-05", average_rate: 350, high_rate: 420, low_rate: 310, volume_traded_kg: 740 },

  // 7-day history for Laptops
  { history_id: "hist-lap-1", material_id: "laptops", recorded_date: "2026-08-30", average_rate: 208, high_rate: 235, low_rate: 185, volume_traded_kg: 310 },
  { history_id: "hist-lap-2", material_id: "laptops", recorded_date: "2026-08-31", average_rate: 209, high_rate: 238, low_rate: 188, volume_traded_kg: 340 },
  { history_id: "hist-lap-3", material_id: "laptops", recorded_date: "2026-09-01", average_rate: 210, high_rate: 240, low_rate: 190, volume_traded_kg: 390 },
  { history_id: "hist-lap-4", material_id: "laptops", recorded_date: "2026-09-02", average_rate: 210, high_rate: 240, low_rate: 190, volume_traded_kg: 420 },
  { history_id: "hist-lap-5", material_id: "laptops", recorded_date: "2026-09-03", average_rate: 211, high_rate: 240, low_rate: 190, volume_traded_kg: 460 },
  { history_id: "hist-lap-6", material_id: "laptops", recorded_date: "2026-09-04", average_rate: 210, high_rate: 240, low_rate: 190, volume_traded_kg: 510 },
  { history_id: "hist-lap-7", material_id: "laptops", recorded_date: "2026-09-05", average_rate: 210, high_rate: 240, low_rate: 190, volume_traded_kg: 490 }
];

export const RECYCLERS_SEED = [
  {
    recycler_id: "rec-apex",
    name: "Apex E-Recovery Ltd.",
    badge: "CPCB Authorized • Grade A",
    cpcb_registration_no: "CPCB/EPR-REC/2023/MH-0149",
    registration_valid_till: "2028-03-31",
    status: "VERIFIED_ACTIVE",
    facility_location: "Turbhe MIDC, Navi Mumbai",
    latitude: 19.0825,
    longitude: 73.0182,
    contact_phone: "+91 98201 12345",
    rating: 4.9,
    intake_capacity_kg_day: 4000,
    current_intake_kg: 2150,
    pickup_capability: true,
    pickup_vehicle_type: "Tata Ace EV (1.2T)",
    pickup_radius_km: 25,
    accepted_materials: ["smartphones", "laptops", "pcb", "cables", "motors_magnets"],
    settlement_modes: ["CASH_IMMEDIATE", "UPI_INSTANT"]
  },
  {
    recycler_id: "rec-ecobirbal",
    name: "EcoBirbal Circular Metals",
    badge: "CPCB Authorized • R-Refiner",
    cpcb_registration_no: "CPCB/EPR-REC/2022/MH-0082",
    registration_valid_till: "2027-12-31",
    status: "VERIFIED_ACTIVE",
    facility_location: "Bhiwandi Logistics Hub, Thane",
    latitude: 19.2812,
    longitude: 73.0483,
    contact_phone: "+91 98922 67890",
    rating: 4.8,
    intake_capacity_kg_day: 8000,
    current_intake_kg: 5200,
    pickup_capability: true,
    pickup_vehicle_type: "Eicher Pro 2049 (2.5T)",
    pickup_radius_km: 40,
    accepted_materials: ["pcb", "laptops", "smartphones", "batteries", "motors_magnets"],
    settlement_modes: ["CASH_IMMEDIATE", "UPI_INSTANT"]
  },
  {
    recycler_id: "rec-maha-green",
    name: "MahaGreen Dismantlers",
    badge: "MPCB & CPCB Registered",
    cpcb_registration_no: "CPCB/EPR-REC/2024/MH-0311",
    registration_valid_till: "2029-06-30",
    status: "VERIFIED_ACTIVE",
    facility_location: "Kurla Industrial Estate, Mumbai",
    latitude: 19.0657,
    longitude: 72.8794,
    contact_phone: "+91 97690 11223",
    rating: 4.7,
    intake_capacity_kg_day: 2000,
    current_intake_kg: 1100,
    pickup_capability: true,
    pickup_vehicle_type: "Electric Cargo 3-Wheeler",
    pickup_radius_km: 15,
    accepted_materials: ["smartphones", "laptops", "cables", "crt", "abs_plastic"],
    settlement_modes: ["CASH_IMMEDIATE", "UPI_INSTANT"]
  },
  {
    recycler_id: "rec-safebat",
    name: "SafeCell Battery Solutions",
    badge: "CPCB Hazardous Waste Recycler",
    cpcb_registration_no: "CPCB/HAZ-BAT/2023/MH-0044",
    registration_valid_till: "2027-09-30",
    status: "VERIFIED_ACTIVE",
    facility_location: "Taloja Chemical Zone, Navi Mumbai",
    latitude: 19.0254,
    longitude: 73.1121,
    contact_phone: "+91 98334 55667",
    rating: 4.9,
    intake_capacity_kg_day: 5000,
    current_intake_kg: 3400,
    pickup_capability: true,
    pickup_vehicle_type: "Hazmat Certified Container EV",
    pickup_radius_km: 50,
    accepted_materials: ["batteries"],
    settlement_modes: ["CASH_IMMEDIATE", "UPI_INSTANT"]
  }
];

export const COLLECTOR_SEED = {
  id: "COL-MUM-8402",
  collector_id: "COL-MUM-8402",
  name: "Ramesh Pawar",
  phone: "+91 98200 48402",
  role: "Informal E-Waste Aggregator",
  operating_location: "Kurla West Scrap Cluster, Mumbai",
  serviceArea: "Kurla West Scrap Cluster, Mumbai",
  preferred_language: "hi",
  compliance_tier: "Tier 1 Verified (Field Partner)",
  total_lots_completed: 29,
  totalLotsCompleted: 29,
  monthly_weight_kg: 482.5,
  monthlyWeightKg: 482.5,
  monthly_earnings_inr: 89450,
  monthlyEarningsInr: 89450
};

export const INITIAL_LOTS_SEED = [
  {
    lotId: "EW-2041",
    collectorId: "COL-MUM-8402",
    materialId: "laptops",
    subCategory: "Portable Notebook PC Units",
    cpcbCategoryCode: "ITEW2",
    materialName: "Laptops & Notebooks",
    materialDescription: "Mixed Intel Core-i3/i5 enterprise laptops, complete chassis with screens intact",
    condition: "INTACT",
    sourceType: "COMMERCIAL_OFFICE",
    photoReference: "/assets/sample_photos/laptops_batch.jpg",
    reportedWeightKg: 12.4,
    actualIntakeWeightKg: 13.0,
    weightVarianceKg: 0.6,
    estimatedValue: 2604,
    quotedPricePerKg: 210,
    finalNetPayout: 2730,
    selectedRecyclerId: "rec-apex",
    selectedRecyclerName: "Apex E-Recovery Ltd.",
    status: "SETTLED",
    paymentStatus: "CASH_SETTLED",
    paymentMode: "CASH_IMMEDIATE",
    collectionLocation: "Kurla West Scrap Market, Mumbai",
    handoverLocation: "Apex E-Recovery Gate 2, Turbhe MIDC",
    handoverLat: 19.082500,
    handoverLng: 73.018200,
    handoverAccuracyM: 4.8,
    gpsTimestamp: "2026-09-04T11:45:12Z",
    gpsFixType: "HARDWARE_GNSS_L1_L5",
    handoverReferenceNo: "HOR-2041-APX",
    form6ManifestUrl: "https://cpcb-trace.nic.in/epr/manifest/MH-2041",
    qrCodePayload: "EWB:LOT=EW-2041:REC=rec-apex:WT=13.0:CPCB=ITEW2:GPS=19.0825,73.0182:SIG=8f9a2b",
    settledAt: "2026-09-04T14:30:00Z",
    createdAt: "2026-09-04T10:15:00Z",
    events: [
      { step: "CREATED", timestamp: "2026-09-04T10:15:00Z", agent: "Ramesh Pawar", latitude: 19.0688, longitude: 72.8792, note: "Lot registered with 12.4 kg reported weight" },
      { step: "MATCHED", timestamp: "2026-09-04T10:18:00Z", agent: "Apex E-Recovery", latitude: 19.0825, longitude: 73.0182, note: "Accepted offer at ₹210/kg + ₹25 EPR incentive" },
      { step: "PICKUP_DISPATCHED", timestamp: "2026-09-04T11:45:00Z", agent: "Tata Ace EV (MH-04-AZ-4412)", latitude: 19.0825, longitude: 73.0182, note: "Handover verified via Form-6 QR scan + GPS Fix (±4.8m)" },
      { step: "INTAKE_VERIFIED", timestamp: "2026-09-04T14:15:00Z", agent: "Weighbridge Station 01", latitude: 19.0825, longitude: 73.0182, note: "Gross: 13.0 kg, Moisture: 0%, Certified Grade A" },
      { step: "SETTLED", timestamp: "2026-09-04T14:30:00Z", agent: "Apex Accounts", latitude: 19.0825, longitude: 73.0182, note: "Spot cash ₹2,730 paid immediately to collector" }
    ]
  },
  {
    lotId: "EW-2042",
    collectorId: "COL-MUM-8402",
    materialId: "cables",
    subCategory: "PVC Insulated Copper Wire Spools",
    cpcbCategoryCode: "NFM1",
    materialName: "Copper Wires & Cables",
    materialDescription: "Mixed high-conductivity building wire and computer power cables",
    condition: "SCRAP",
    sourceType: "INFORMAL_AGGREGATOR",
    photoReference: "/assets/sample_photos/cables_copper.jpg",
    reportedWeightKg: 18.0,
    actualIntakeWeightKg: 18.0,
    weightVarianceKg: 0.0,
    estimatedValue: 3240,
    quotedPricePerKg: 180,
    finalNetPayout: 3240,
    selectedRecyclerId: "rec-maha-green",
    selectedRecyclerName: "MahaGreen Dismantlers",
    status: "SETTLED",
    paymentStatus: "CASH_SETTLED",
    paymentMode: "CASH_IMMEDIATE",
    collectionLocation: "Sakinaka Junction, Andheri East",
    handoverLocation: "MahaGreen Yard 3, Kurla",
    handoverLat: 19.072831,
    handoverLng: 72.899210,
    handoverAccuracyM: 3.2,
    gpsTimestamp: "2026-09-04T15:45:00Z",
    gpsFixType: "HARDWARE_GNSS_L1_L5",
    handoverReferenceNo: "HOR-2042-MHG",
    form6ManifestUrl: "https://cpcb-trace.nic.in/epr/manifest/MH-2042",
    qrCodePayload: "EWB:LOT=EW-2042:REC=rec-maha-green:WT=18.0:CPCB=NFM1:GPS=19.0728,72.8992:SIG=3c4d5e",
    settledAt: "2026-09-04T16:00:00Z",
    createdAt: "2026-09-04T12:00:00Z",
    events: [
      { step: "CREATED", timestamp: "2026-09-04T12:00:00Z", agent: "Ramesh Pawar", latitude: 19.1025, longitude: 72.8872, note: "18.0 kg copper cables registered (Safe handling: No open burning)" },
      { step: "MATCHED", timestamp: "2026-09-04T12:05:00Z", agent: "MahaGreen Dismantlers", latitude: 19.0728, longitude: 72.8992, note: "Hyperlocal pickup confirmed at ₹180/kg" },
      { step: "SETTLED", timestamp: "2026-09-04T16:00:00Z", agent: "MahaGreen Accounts", latitude: 19.0728, longitude: 72.8992, note: "Cash ₹3,240 settled upon mechanical shredder intake" }
    ]
  },
  {
    lotId: "EW-2043",
    collectorId: "COL-MUM-8402",
    materialId: "motors_magnets",
    subCategory: "Neodymium Hard Drive & Motor Assemblies",
    cpcbCategoryCode: "EEM1",
    materialName: "Motors & Magnet Assemblies",
    materialDescription: "Mixed server fan stators and voice-coil permanent magnets",
    condition: "PARTIAL_DISMANTLED",
    sourceType: "COMMERCIAL_OFFICE",
    photoReference: "/assets/sample_photos/motors_magnets.jpg",
    reportedWeightKg: 25.0,
    actualIntakeWeightKg: null,
    weightVarianceKg: null,
    estimatedValue: 3000,
    quotedPricePerKg: 120,
    finalNetPayout: 3000,
    selectedRecyclerId: "rec-ecobirbal",
    selectedRecyclerName: "EcoBirbal Circular Metals",
    status: "IN_TRANSIT",
    paymentStatus: "HELD_IN_ESCROW",
    paymentMode: "CASH_IMMEDIATE",
    collectionLocation: "Kurla West Scrap Market, Mumbai",
    handoverLocation: "EcoBirbal Processing Facility, Bhiwandi",
    handoverLat: 19.281240,
    handoverLng: 73.048320,
    handoverAccuracyM: 5.1,
    gpsTimestamp: "2026-09-05T10:45:00Z",
    gpsFixType: "NETWORK_ASSISTED_GPS",
    handoverReferenceNo: "HOR-2043-EBR",
    form6ManifestUrl: "https://cpcb-trace.nic.in/epr/manifest/MH-2043",
    qrCodePayload: "EWB:LOT=EW-2043:REC=rec-ecobirbal:WT=25.0:CPCB=EEM1:GPS=19.2812,73.0483:SIG=7a8b9c",
    settledAt: null,
    createdAt: "2026-09-05T09:30:00Z",
    events: [
      { step: "CREATED", timestamp: "2026-09-05T09:30:00Z", agent: "Ramesh Pawar", latitude: 19.0688, longitude: 72.8792, note: "25 kg rare earth motor assemblies logged via Voice AI" },
      { step: "MATCHED", timestamp: "2026-09-05T09:34:00Z", agent: "EcoBirbal Circular Metals", latitude: 19.2812, longitude: 73.0483, note: "Offered top benchmark ₹120/kg + EV transport" },
      { step: "PICKUP_DISPATCHED", timestamp: "2026-09-05T11:00:00Z", agent: "Eicher Pro 2049", latitude: 19.2812, longitude: 73.0483, note: "Loaded into secured logistics container. In transit to weighbridge." }
    ]
  },
  {
    lotId: "EW-2044",
    collectorId: "COL-MUM-8402",
    materialId: "lcd_panels",
    subCategory: "Liquid Crystal Display & LED Flat Panels",
    cpcbCategoryCode: "ITEW12",
    materialName: "LCD & LED Display Panels",
    materialDescription: "Assorted flat screen monitor displays with CCFL backlights intact (Indium recovery batch)",
    condition: "SCRAP",
    sourceType: "COMMERCIAL_OFFICE",
    photoReference: "/assets/sample_photos/lcd_panels_batch.jpg",
    reportedWeightKg: 22.0,
    actualIntakeWeightKg: 22.0,
    weightVarianceKg: 0.0,
    estimatedValue: 1430,
    quotedPricePerKg: 65,
    finalNetPayout: 1430,
    selectedRecyclerId: "rec-apex",
    selectedRecyclerName: "Apex E-Recovery Ltd.",
    status: "SETTLED",
    paymentStatus: "CASH_SETTLED",
    paymentMode: "CASH_IMMEDIATE",
    collectionLocation: "Dharavi Transit Center, Mumbai",
    handoverLocation: "Apex E-Recovery Gate 1, Turbhe MIDC",
    handoverLat: 19.082500,
    handoverLng: 73.018200,
    handoverAccuracyM: 4.2,
    gpsTimestamp: "2026-09-05T13:20:00Z",
    gpsFixType: "HARDWARE_GNSS_L1_L5",
    handoverReferenceNo: "HOR-2044-APX",
    form6ManifestUrl: "https://cpcb-trace.nic.in/epr/manifest/MH-2044",
    qrCodePayload: "EWB:LOT=EW-2044:REC=rec-apex:WT=22.0:CPCB=ITEW12:GPS=19.0825,73.0182:SIG=9e1f2a",
    settledAt: "2026-09-05T14:10:00Z",
    createdAt: "2026-09-05T11:00:00Z",
    events: [
      { step: "CREATED", timestamp: "2026-09-05T11:00:00Z", agent: "Ramesh Pawar", latitude: 19.0431, longitude: 72.8524, note: "22 kg flat LCD screens registered (Safe handling: No glass crushing)" },
      { step: "MATCHED", timestamp: "2026-09-05T11:15:00Z", agent: "Apex E-Recovery", latitude: 19.0825, longitude: 73.0182, note: "Accepted at ₹65/kg benchmark rate for Indium extraction" },
      { step: "PICKUP_DISPATCHED", timestamp: "2026-09-05T12:30:00Z", agent: "Tata Ace EV (MH-04-AZ-4412)", latitude: 19.0825, longitude: 73.0182, note: "Handover confirmed via GNSS coordinates (19.0825° N, 73.0182° E, ±4.2m)" },
      { step: "SETTLED", timestamp: "2026-09-05T14:10:00Z", agent: "Apex Accounts", latitude: 19.0825, longitude: 73.0182, note: "Cash ₹1,430 paid in spot settlement" }
    ]
  }
];

export const BUYER_DEMANDS_SEED = [
  {
    id: "dem-101",
    recyclerId: "rec-apex",
    recyclerName: "Apex E-Recovery",
    materialId: "laptops",
    requiredQuantityKg: 500,
    fulfilledQuantityKg: 310,
    offeredRatePerKg: 215,
    pickupRadiusKm: 25,
    status: "URGENT",
    expiresAt: "2026-09-08T18:00:00Z"
  },
  {
    id: "dem-102",
    recyclerId: "rec-ecobirbal",
    recyclerName: "EcoBirbal Metals",
    materialId: "pcb",
    requiredQuantityKg: 800,
    fulfilledQuantityKg: 520,
    offeredRatePerKg: 365,
    pickupRadiusKm: 40,
    status: "URGENT",
    expiresAt: "2026-09-09T18:00:00Z"
  },
  {
    id: "dem-103",
    recyclerId: "rec-safebat",
    recyclerName: "SafeCell Battery",
    materialId: "batteries",
    requiredQuantityKg: 1200,
    fulfilledQuantityKg: 780,
    offeredRatePerKg: 102,
    pickupRadiusKm: 50,
    status: "OPEN",
    expiresAt: "2026-09-10T18:00:00Z"
  }
];

export const FIELD_RESEARCH_CASE_STUDIES = [
  {
    id: "case-01",
    collectorName: "Ramu Pawar",
    age: 42,
    cluster: "Kurla West Scrap Market / Dharavi Periphery, Mumbai",
    experienceYears: 18,
    dailyCollectionKg: "15 - 25 kg mixed electronics & copper wiring",
    baselineMonthlyIncome: 17500,
    platformProjectedIncome: 24800,
    incomeGainPercent: 41.7,
    keyQuotes: {
      hi: "पहले हम तार जलाकर तांबा निकालते थे क्योंकि कबाड़ी प्लास्टिक का पैसा काट लेता था। ऐप पर बिना जलाए पूरा दाम मिला और पुलिस की कोई परेशानी नहीं हुई।",
      mr: "आधी वायर जाळून तांबे काढत होतो. आता ऍपवर भाव समजल्यामुळे आणि कपातीशिवाय रोख पैसे मिळाल्यामुळे काम सोपे झाले."
    },
    criticalFindings: [
      "Informal middlemen were taking a 35-40% cut on market benchmark rates.",
      "Backyard wire burning caused severe respiratory symptoms and soot fines.",
      "Zero digital literacy: cannot type in English; voice mode in Marathi/Hindi is an absolute prerequisite.",
      "Requires immediate spot cash on handover to pay for daily food expenses."
    ]
  },
  {
    id: "case-02",
    collectorName: "Santosh Shinde",
    age: 38,
    cluster: "Hadapsar Aggregator Godown, Pune",
    experienceYears: 11,
    dailyCollectionKg: "800 - 1200 kg monthly aggregator volume",
    baselineMonthlyIncome: 36000,
    platformProjectedIncome: 51200,
    incomeGainPercent: 42.2,
    keyQuotes: {
      hi: "हमारे पास 14 लड़के कचरा लाते हैं। CPCB नियमों का डर था कि दुकान सील न हो जाए। अब सीधे अधिकृत रीसायकलर्स से पक्की रसीद मिलती है।",
      mr: "आमच्याकडे १४ मुले माल आणतात. थेट फॅक्टरीशी संपर्क झाल्यामुळे भाव वाढला आणि जीएसटी/फॉर्म-६ पावतीमुळे अधिकृत व्यवसाय सुरू झाला."
    },
    criticalFindings: [
      "Aggregates from 14 street waste-pickers; operates as critical first-tier hub.",
      "Feared formalization due to complex paperwork and tax harassment.",
      "Platform Form-6 QR manifest provided legal protection against local police extortion.",
      "Certified weighbridge integration eliminated gross/tare weight disputes."
    ]
  }
];

export const UNIT_ECONOMICS_DATA = {
  informalVsPlatformTable: [
    {
      stream: "Laptop Scrap (10 kg)",
      informalRate: 140,
      informalPayout: 1400,
      platformRate: 210,
      platformPayout: 2100,
      netGain: 700,
      gainPercent: "+50.0%"
    },
    {
      stream: "Motherboards / PCBs (5 kg)",
      informalRate: 220,
      informalPayout: 1100,
      platformRate: 350,
      platformPayout: 1750,
      netGain: 650,
      gainPercent: "+59.1%"
    },
    {
      stream: "Copper Wires (15 kg)",
      informalRate: 125,
      informalPayout: 1875,
      platformRate: 180,
      platformPayout: 2700,
      netGain: 825,
      gainPercent: "+44.0%"
    },
    {
      stream: "Li-Ion Batteries (10 kg)",
      informalRate: 60,
      informalPayout: 600,
      platformRate: 95,
      platformPayout: 950,
      netGain: 350,
      gainPercent: "+58.3%"
    },
    {
      stream: "Motors & Magnets (20 kg)",
      informalRate: 75,
      informalPayout: 1500,
      platformRate: 120,
      platformPayout: 2400,
      netGain: 900,
      gainPercent: "+60.0%"
    }
  ],
  monthlyTotals: {
    informalMonthlyNet: 18450,
    platformMonthlyNet: 25980,
    monthlyGainInr: 7530,
    percentageIncrease: 40.8
  },
  platformSustainabilityModel: {
    collectorFee: "₹0.00 (100% Free Forever for Informal Waste-Pickers)",
    recyclerFacilitationFee: "1.75% of Settled Intake Value (Paid by CPCB Recycler)",
    whyRecyclersPay: "Saves 12-18% broker markup while securing verified CPCB Form-6 EPR compliance credits",
    serverlessEdgeOpex: "₹0.00 / month on local edge neural models (no recurring cloud API bills)"
  }
};
